### PR TITLE
Add support of Flask blueprints

### PR DESCRIPTION
**Pull request by oblalex**
Hi,

I'd like to introduce support of [Flask blueprints](http://flask.pocoo.org/docs/latest/blueprints/).

Docs, package version and changelog are updated as well.

### CODE REVIEW

**Comment by AzureusNation** [comment]
Bravo sir, I would love to see this implemented and merged.

**Comment by ptallada** [comment]
Yes, I would love that too :)

**Comment by ondoheer** [comment]
Yes, it's a good addition

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by oblalex** [comment]
Wow, thanks man.

My next step is to add class-based `WebSocketView`. Does this makes interest?

**Comment by kennethreitz** [comment]
That sounds like it would be very welcome, if done right! I'm not exactly sure what it would look like, off the top of my head, but I'm sure you do ;)

**Comment by oblalex** [comment]
Sounds good, going to take this into the progress soon.

**Comment by kennethreitz** [comment]
@oblalex would you be interested in helping to maintain this library?

**Comment by oblalex** [comment]
@kennethreitz Feels to be nice, seems like I'm already helping :) I can see some issues on GH which are related to functionality and docs. I'll see what I can do with my time.

**Comment by kennethreitz** [comment]
@oblalex don't break anything ;)

**Comment by oblalex** [comment]
@kennethreitz wow, thanks!

**Pull request merged**
